// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xydxefpsupwbycpjictq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5ZHhlZnBzdXB3YnljcGppY3RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2NTkyMDAsImV4cCI6MjA1MzIzNTIwMH0.HdorTMEsStA1oGjUXC2Vfc8lhgrZVWv2q-TMIqnRvh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
